export const options = {
    minColor: "#db366e",
    midColor: "#a955d4",
    maxColor: "#275fd2",
    headerHeight: 0,
    showScale: false,
    highlightOnMouseOver: false,
    highlightColor: "black",
    highlightBorder: "none",
    highlightBorderWidth: 0,
    enableHighlight: false,
    borders: false,
    borderWidth: 0,
    font: {
        size: 13,
        family: "Roboto",
        bold: false,
        italic: false,
        color: "white"
    }
};

// export const data = [
//     [
//         "Location",
//         "Parent",
//         "Hours",
//         "Qualification",
//     ],
//     ["All", null, 0, 0],
//     ["Carpenter", "All", 0, 0],
//     ["Roofing", "All", 0, 0],
//     ["Concrete", "All", 0, 0],
//     ["Building Walls", "Carpenter", 11, 10],
//     ["Moving Material", "Carpenter", 52, 31],
//     ["Installing Tyvek", "Carpenter", 24, 12],
//     ["Clean-Up Carpenter", "Carpenter", 16, -23],
//     ["Setting Floor Joist", "Carpenter", 42, -11],
//     ["Set-Up Carpenter", "Carpenter", 31, -2],
//     ["Setting Trusses", "Carpenter", 22, -13],
//     ["Roof Sheeting", "Carpenter", 17, 4],
//     ["Exterior Wall Sheeting", "Carpenter", 21, -5],
//     ["Building Stair Systems", "Carpenter", 36, 4],
//     ["Building Gables", "Carpenter", 20, -12],
//     ["Layouts", "Carpenter", 40, 63],
//     ["Floor Decking", "Carpenter", 4, 34],
//     ["Misc Carpentry", "Carpenter", 1, -5],
//     ["Roofing Installation", "Roofing", 12, 24],
//     ["Tear Off", "Roofing", 18, 13],
//     ["Ridge Cap/Vent", "Roofing", 11, -52],
//     ["Clean-Up Roofer", "Roofing", 21, 0],
//     ["Underlayment Installation", "Roofing", 30, 43],
//     ["Edge Metal Installation", "Roofing", 12, 2],
//     ["Misc Roofing", "Roofing", 10, 12],
//     ["Valley Installation", "Roofing", 8, 10],
//     ["Decking/Sheeting Installation", "Roofing", 8, 10],
//     ["Lifetime Shingle Installation", "Roofing", 8, 10],
//     ["Penetration Installation", "Roofing", 8, 10],
//     ["Moving Gravel", "Roofing", 8, 10],
//     ["Setting Forms", "Concrete", 8, 10],
//     ["Puddling", "Concrete", 8, 10],
//     ["Pulling Forms", "Concrete", 8, 10],
//     ["Clean-Up Concrete", "Concrete", 8, 10],
//     ["Set-Up Concrete", "Concrete", 8, 10],
// ];
