export const wrapped_data = [
    ["Work", "Parent", "Hours", "Qualification"],
    ["All", "", 0, 0],
    ["Carpenter", "All", 0, 0],
    ["Roofing", "All", 0, 0],
    ["Concrete", "All", 0, 0],
    ["Building Walls", "Carpenter", 417, 18],
    ["Moving Material", "Carpenter", 209, 35],
    ["Installing Tyvek", "Carpenter", 49, 18],
    ["Clean-Up Carpenter", "Carpenter", 16, -23],
    ["Setting Floor Joist", "Carpenter", 28, 18],
    ["Set-Up Carpenter", "Carpenter", 31, -2],
    ["Setting Trusses", "Carpenter", 584, 90],
    ["Roof Sheeting", "Carpenter", 0, 18],
    ["Exterior Wall Sheeting", "Carpenter", 95, 18],
    ["Building Stair Systems", "Carpenter", 159, 35],
    ["Building Gables", "Carpenter", 415, 76],
    ["Layouts", "Carpenter", 93, 35],
    ["Floor Decking", "Carpenter", 540, 90],
    ["Misc Carpentry", "Carpenter", 610, 90],
    ["Roofing Installation", "Roofing", 461, 35],
    ["Tear Off", "Roofing", 1494, 90],
    ["Ridge Cap/Vent", "Roofing", 886, 76],
    ["Clean-Up Roofer", "Roofing", 21, 0],
    ["Underlayment Installation", "Roofing", 570, 76],
    ["Edge Metal Installation", "Roofing", 883, 76],
    ["Misc Roofing", "Roofing", 10, 12],
    ["Valley Installation", "Roofing", 129, 18],
    ["Decking/Sheeting Installation", "Roofing", 103, 35],
    ["Lifetime Shingle Installation", "Roofing", 147, 90],
    ["Penetration Installation", "Roofing", 6, 35],
    ["Moving Gravel", "Roofing", 435, 35],
    ["Setting Forms", "Concrete", 203, 35],
    ["Puddling", "Concrete", 640, 35],
    ["Pulling Forms", "Concrete", 177, 18],
    ["Clean-Up Concrete", "Concrete", 8, 10],
    ["Set-Up Concrete", "Concrete", 8, 10],
]
